image: debian/stable
packages:
  - build-essential
  - pkg-config
  - curl
secrets:
  - 1aeb435f-7837-4290-9e6e-915401a14d6e
sources:
  - git@git.sr.ht:~kvsari/derive-getters
tasks:
  - setup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
      chmod +x rustup.sh
      ./rustup.sh -y
      cat .cargo/env >> .buildenv
  - build: |
      cd scl
      cargo build
      cargo build --release
  - test: |
      cd scl
      cargo test
      cargo test --release
